package com.muhammedelsami.storepilot.gradle

import com.muhammedelsami.storepilot.engine.config.ConfigParser
import com.muhammedelsami.storepilot.engine.config.configName
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import kotlin.io.path.invariantSeparatorsPathString
import kotlin.io.path.writeText

/**
 * `exportStorepilotConfig`: writes the DSL as `storepilot.yml`, so that the CLI and the action use the
 * same settings (docs/design.md §6). Credentials are never written.
 */
@DisableCachingByDefault(because = "Writes a small file into the project")
abstract class ExportConfigTask : StorePilotTask() {
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun export() {
        val file = outputFile.get().asFile.toPath()
        val metadataDir = file.parent.relativize(metadataDir.get().asFile.toPath()).invariantSeparatorsPathString
        val text = buildString {
            appendLine("# Generated by ./gradlew exportStorepilotConfig. Credentials are not stored here (docs/design.md §8).")
            appendLine("version: ${ConfigParser.VERSION}")
            appendLine("metadataDir: ${quote(metadataDir.ifEmpty { "." })}")
            appendLine("onUnsupported: ${onUnsupported.get().configName}")
            appendLine("fallbackToDefaultLanguage: ${fallbackToDefaultLanguage.get()}")
            appendLine("listing:")
            appendLine("  graphics: ${listingGraphics.get()}")
            appendLine("  replaceScreenshots: ${replaceScreenshots.get()}")
            appendLine("aso:")
            appendLine("  disable: [" + disabledLintRules.get().sorted().joinToString(", ") + "]")
            appendLine("  warningsAsErrors: ${warningsAsErrors.get()}")
            appendLine("stores:")
            appendLine("  ${store.get()}:")
            val packageName = packageName.orNull ?: applicationIds.get().distinct().singleOrNull()
            packageName?.let { appendLine("    packageName: ${quote(it)}") }
            track.orNull?.let { appendLine("    track: ${quote(it)}") }
            rollout.orNull?.let { appendLine("    rollout: $it") }
            releaseStatus.orNull?.let { appendLine("    releaseStatus: ${it.configName}") }
            storeOptions.get().toSortedMap().forEach { (key, value) -> appendLine("    $key: ${quote(value)}") }
        }
        file.writeText(text)
        logger.lifecycle("Wrote $file")
    }

    private fun quote(value: String) = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
